spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    properties:
      hibernate.format_sql: true
    hibernate:
      ddl-auto: create

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 607795509178-hepl5hch2l00d3igftdbcs6e5vkiip7k.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - openid
              - profile
          okta:
            client-id: 0oaa291221aCE68cd5d7
            client-secret: 1mWNHtpaBGu52QNlDuM2JLc5JVuCOBL611_lGCu-
        provider:
          okta:
            authorization-uri: https://dev-34251156.okta.com/oauth2/default/v1/authorize
            token-uri: https://dev-34251156.okta.com/oauth2/default/v1/token
            user-info-uri: https://dev-34251156.okta.com/oauth2/default/v1/userinfo
            jwk-set-uri: https://dev-34251156.okta.com/oauth2/default/v1/keys
            issuer-uri: https://dev-34251156.okta.com/oauth2/default

          google:
            issuer-uri: https://accounts.google.com
            user-name-attribute: email

okta:
  oauth2:
    issuer: https://dev-34251156.okta.com/oauth2/default
    clientId: 0oaa291221aCE68cd5d7
    clientSecret: 1mWNHtpaBGu52QNlDuM2JLc5JVuCOBL611_lGCu-
    audience: api://default
    groups-claim: groups